Unit VPIPC;
{ ************************************************************************** }
{ }
{ This C DLL header file first (automatic) conversion generated by: }
{ HeadConv 4.0 (c) 2000 by Bob Swart (aka Dr.Bob - www.drbob42.com) }
{ Final Delphi-Jedi (Darth) command-line units edition }
{ }
{ Generated Date:  14/8/2018 }
{ Generated Time: 20:59:39 }
{ }
{ ************************************************************************** }

interface

uses
{$IFDEF WIN32}
  Windows;
{$ELSE}
  Wintypes, WinProcs;
{$ENDIF}
{ => VPIPC.H <= }

{$IFNDEF _VPIPC_H_}
{$DEFINE _VPIPC_H_}
{ +//* }
{ -* VpiPc.h }
{ -* Contiene la declaración de la sunciones que implementan la comunicación }
{ -* utilizando el protocolo IngStore, entre una PC y un POS Ingenico con la }
{ -* aplicación de VISA con POS Integrado. }
{ = }

{ +//* }
{ -* Codigos de retorno de las funciones }
{ = }
const
  VPI_OK = 0;                 { // Operacion exitosa }
  VPI_MORE_REC = 1;           { // Operacion exitosa, pero faltan registros }

const
  VPI_FAIL = 11;              { // El comando no pudo ser enviado }
  VPI_TIMEOUT_EXP = 12;       { // Tiempo de espera agotado. }

const
  VPI_INVALID_ISSUER = 101;   { // El código de tarjeta no existe. }
  VPI_INVALID_TICKET = 102;   { // El número de cupón no existe. }
  VPI_INVALID_PLAN = 103;     { // El código de plan no existe. }
  VPI_INVALID_INDEX = 104;    { // No existe el indice }
  VPI_EMPTY_BATCH = 105;      { // El lote del POS se encuentra vacío. }

const
  VPI_TRX_CANCELED = 201;     { // Transacción cancelada por el usuario. }
  VPI_DIF_CARD = 202;         { // La tarjeta deslizada por el usuario no coincide con la pedida. }
  VPI_INVALID_CARD = 203;     { // La tarjeta deslizada no es válida. }
  VPI_EXPIRED_CARD = 204;     { // La tarjeta deslizada está vencida. }
  VPI_INVALID_TRX = 205;      { // La transacción original no existe. }

const
  VPI_ERR_COM = 301;          { // El POS no pudo comunicarse con el host. }
  VPI_ERR_PRINT = 302;        { // El POS no pudo imprimir el ticket. }

const
  VPI_INVALID_IN_CMD = 901;   { // Nombre del comando inexistente. }
  VPI_INVALID_IN_PARAM = 902; { // Formato de algún parámetro de entrada no es correcto. }
  VPI_INVALID_OUT_CMD = 903;  { // El comando enviado por }
  VPI_GENERAL_FAIL = 909;     { // Error general en la operación. }

  { +//* }
  { -* Codigos de las operaciones }
  { = }

const
  VPI_PURCHASE = 1;     { // Venta }
  VPI_VOID = 2;         { // Anulación de venta }
  VPI_REFUND = 3;       { // Devolución }
  VPI_REFUND_VOID = 4;  { // Anulación de devolución }

  { +//* }
  { -* Timeouts }
  { = }
const
  VPI_TIMEOUT_STD = 3000;   { // Timeout mínimo 3 segundos }
  VPI_TIMEOUT_HIG = 60000;  { // Timeout alto 60 segundos }
  VPI_TIMEOUT_LOW = 10000;  { // Timeout bajo 10 segundos }

  { +//* }
  { -* Parámetros de configuración del puerto serial. }
  { = }
type
  Com_Params = record
    com: pAnsiChar;
    baudRate: Word;
    byteSize: Word;
    parity: Char;
    stopBits: Word;
  end { COM_PARAMS };

  pComParams_t = Com_Params;

  { +//* }
  { -* Parametros de entrada para la funcion de Venta }
  { = }
type
  purchase_in = record
    amount: PAnsiChar;
    receiptNumber: PAnsiChar;
    instalmentCount: PAnsiChar;
    issuerCode: PAnsiChar;
    planCode: PAnsiChar;
    tip: PAnsiChar;
    merchantCode: PAnsiChar;
    merchantName: PAnsiChar;
    cuit: PAnsiChar;
    linemode: byte;
  end { PURCHASE_IN };

  vpiPurchaseIn_t = purchase_in;

  { +//* }
  { -* Parametros de entrada para la funcion de Anulacion }
  { = }
type
  Void_in = record
    originalTicket: PAnsiChar;
    issuerCode: PAnsiChar;
    merchantName: PAnsiChar;
    cuit: PAnsiChar;
  end { VOID_IN };

  vpiVoidIn_t = Void_in;

  { +//* }
  { -* Parametros de entrada para la funcion de Devolucion }
  { = }
type
  refund_in = record
    amount: PAnsiChar;
    instalmentCount: PAnsiChar;
    issuerCode: PAnsiChar;
    planCode: PAnsiChar;
    originalTicket: PAnsiChar;
    originalDate: PAnsiChar;
    receiptNumber: PAnsiChar;
    merchantCode: PAnsiChar;
    merchantName: PAnsiChar;
    cuit: PAnsiChar;
    linemode: byte;
  end { REFUND_IN };
  vpiRefundIn_t = refund_in;

  { +//* }
  { -* Parametros de salida para las funciones de Venta, Anulacion y Devolucion }
  { = }
type
  trx_out = record
    hostRespCode: PAnsiChar;
    hostMessage: PAnsiChar;
    authCode: PAnsiChar;
    ticketNumber: PAnsiChar;
    batchNumber: PAnsiChar;
    customerName: PAnsiChar;
    { +// Eldar MOD --->*/ }
    panFirst6: PAnsiChar;
    { +// <--- Eldar MOD*/ }
    panLast4: PAnsiChar;
    date: PAnsiChar;
    time: PAnsiChar;
    terminalID: PAnsiChar;
  end { TRX_OUT };
  vpiTrxOut_T = trx_out;

  { +//* }
  { -* Parametros de salida de la funcion de Cierre de lote. }
  { = }
type
  BatchCloseOut = record
    hostRespCode: PAnsiChar;
    date: PAnsiChar;
    time: PAnsiChar;
    terminalID: PAnsiChar;
  end { BATCHCLOSE_OUT };

  vpiBatchCloseOut_T = BatchCloseOut;

  { +//* }
  { -* Registro con los totales por tarjeta del Cierre de lote. }
  { = }
type
  BatchCloseData_Out = record
    index: word;
    acquirerCode: PAnsiChar;
    batchNumber: PAnsiChar;
    issuerCode: PAnsiChar;
    purchaseCount: PAnsiChar;
    purchaseAmount: PAnsiChar;
    voidCount: PAnsiChar;
    voidAmount: PAnsiChar;
    refundCount: PAnsiChar;
    refundAmount: PAnsiChar;
    refvoidCount: PAnsiChar;
    refvoidAmount: PAnsiChar;
    date: PAnsiChar;
    time: PAnsiChar;
    terminalID: PAnsiChar;
  end { BATCHCLOSEDATA_OUT };
  vpiBatchCloseDataOut_T = BatchCloseData_Out;

  { +//* }
  { = }
type
  Issuer_Out = record
    index: Word;
    acquirerCode: PAnsiChar;
    issuerCode: PAnsiChar;
    issuerName: PAnsiChar;
    maxInstCount: PAnsiChar;
    terminalID: PAnsiChar;
  end { ISSUER_OUT };

  vpiIssuerOut_T = Issuer_Out;

  { +//* }
  { = }
type
  Plan_Out = record
    index: Word;
    issuerCode: PAnsiChar;
    planCode: PAnsiChar;
    planLabel: PAnsiChar;
    terminalID: PAnsiChar;
  end { PLAN_OUT };

  vpiPlanOut_t = Plan_Out;

  { +//* }
  { -* Abre el puerto serial de comunicaciones para poder enviar y recibir }
  { -* los comandos.El puerto debe estar cerrado para que la ejecución sea }
  { -* exitosa.Es necesario para ejecutar el resto de los comandos. }
  { -* @param params Parámetros de configuracion del puerto serial. }
  { -* }
  { -* @return VPI_OK Puerto abierto exitosamente }
  { -* @return VPI_FAIL El puerto se encontraba abierto o no se pudo abrir. }
  { = }
var
  vpiOpenPort: function(var params: pComParams_t): Word cdecl
  {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Cierra el puerto serial de comunicaciones y lo deja libre para otras }
  { -* aplicaciones. El puerto debe estar abierto para que la ejecución sea }
  { -* exitosa.Luego de ejecutar este comando, no se puede ejecutar ningun }
  { -* otro comando. }
  { -* @return VPI_OK Puerto cerrado exitosamente }
  { -* @return VPI_FAIL El puerto no se encontraba abierto o no se pudo cerrar. }
  { = }
var
  vpiClosePort: function: Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Envía un mensaje por el puerto y espera la respuesta al mismo en forma }
  { -* sincrónica, para verificar que la conexión con el POS esté OK.La }
  { -* aplicación queda esperando hasta tenga la respuesta o bien expire el }
  { -* timeout default.El puerto debe estar abierto para que la ejecución sea exitosa. }
  { -* @return VPI_OK Conexión exitosa. }
  { -* @return VPI_FAIL No se pudo enviar el comando posiblemente el puerto esté cerrado. }
  { -* @return VPI_TIMEOUT_EXP Timeout de respuesta expirado sin respuesta. }
  { = }
var
  vpiTestConnection: function: Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Envía la orden de realizar una venta y espera la respuesta de la misma en forma }
  { -* sincrónica.La aplicación queda esperando hasta tenga la respuesta o bien expire }
  { -* el timeout especificado.El puerto debe estar abierto para que la ejecución sea }
  { -* exitosa. }
  { -* @param input Estructura con los datos de entrada de la venta. }
  { -* @param output Estructura con los datos de respuesta de la venta. }
  { -* Se completa dentro de la función }
  { -* @param timeout Tiempo de espera de respuesta en segundos. }
  { -* }
  { -* @return VPI_OK }
  { -* @return VPI_FAIL }
  { -* @return VPI_TIMEOUT_EXP }
  { -* @return VPI_INVALID_ISSUER }
  { -* @return VPI_INVALID_PLAN }
  { -* @return VPI_TRX_CANCELED }
  { -* @return VPI_DIF_CARD }
  { -* @return VPI_INVALID_CARD }
  { -* @return VPI_EXPIRED_CARD }
  { -* @return VPI_ERR_COM }
  { -* @return VPI_ERR_PRINT }
  { -* @return VPI_INVALID_IN_CMD }
  { -* @return VPI_INVALID_IN_PARAM }
  { -* @return VPI_INVALID_OUT_CMD }
  { -* @return VPI_GENERAL_FAIL }
  { = }
var
  vpiPurchase: function(var intput: vpiPurchaseIn_t; var output: vpiTrxOut_T;
    timeout: LongInt): Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};

var
  vpiPurchaseExtraCash: function(var intput: vpiPurchaseIn_t; var output: vpiTrxOut_T;
    timeout: LongInt): Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};


  { +//* }
  { -* Envía la orden de realizar una anulación de venta y espera la respuesta de la misma }
  { -* en forma sincrónica.La aplicación queda esperando hasta tenga la respuesta o bien }
  { -* expire el timeout especificado.El puerto debe estar abierto para que la ejecución }
  { -* sea exitosa. }
  { -* @param input Estructura con los datos de entrada de la anulación. }
  { -* @param output Estructura con los datos de respuesta de la anulación. }
  { -* Se completa dentro de la función. }
  { -* @param timeout Tiempo de espera de respuesta en segundos. }
  { -* }
  { -* @return VPI_OK }
  { -* @return VPI_FAIL }
  { -* @return VPI_TIMEOUT_EXP }
  { -* @return VPI_INVALID_IN_CMD }
  { -* @return VPI_INVALID_IN_PARAM }
  { -* @return VPI_INVALID_OUT_CMD }
  { -* @return VPI_GENERAL_FAIL }
  { -* @return VPI_INVALID_ISSUER }
  { -* @return VPI_INVALID_TICKET }
  { -* @return VPI_EMPTY_BATCH }
  { -* @return VPI_TRX_CANCELED }
  { -* @return VPI_DIF_CARD }
  { -* @return VPI_INVALID_CARD }
  { -* @return VPI_EXPIRED_CARD }
  { -* @return VPI_INVALID_TRX }
  { -* @return VPI_ERR_COM }
  { -* @return VPI_ERR_PRINT }

  { = }
var
  vpiVoid: function(var intput: vpiVoidIn_t; var output: vpiTrxOut_T;
    timeout: LongInt): Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Envía la orden de realizar una devolución y espera la respuesta de la misma en }
  { -* forma sincrónica.La aplicación queda esperando hasta tenga la respuesta o bien }
  { -* expire el timeout especificado.El puerto debe estar abierto para que la ejecución }
  { -* sea exitosa. }
  { -* @param input Estructura con los datos de entrada de la devolución. }
  { -* @param output Estructura con los datos de respuesta de la devolución. }
  { -* Se completa dentro de la función. }
  { -* @param timeout Tiempo de espera de respuesta en segundos. }
  { -* }
  { -* @return VPI_OK Conexión exitosa. }
  { -* @return VPI_FAIL No se pudo enviar el comando. }
  { -* @return VPI_TIMEOUT_EXP Timeout de respuesta expirado sin respuesta. }
  { -* @return VPI_INVALID_ISSUER El código de tarjeta no existe. }
  { -* @return VPI_INVALID_PLAN El código de plan no existe. }
  { -* @return VPI_TRX_CANCELED Transacción cancelada por el usuario. }
  { -* @return VPI_DIF_CARD La tarjeta deslizada por el usuario no coincide con la pedida. }
  { -* @return VPI_INVALID_CARD La tarjeta deslizada no es válida. }
  { -* @return VPI_EXPIRED_CARD La tarjeta deslizada está vencida. }
  { -* @return VPI_ERR_COM El POS no pudo comunicarse con el host. }
  { -* @return VPI_ERR_PRINT El POS no pudo imprimir el ticket. }
  { -* @return VPI_INVALID_IN_CMD Nombre del comando inexistente. }
  { -* @return VPI_INVALID_IN_LEN Largo de los parámetros inválido para este comando. }
  { -* @return VPI_INVALID_IN_PARAM Formato de algún parámetro no es correcto. }
  { -* @return VPI_INVALID_OUT_CMD Nombre del comando devuelto no coincide con el enviado. }
  { -* @return VPI_INVALID_OUT_LEN Largo de los parámetros devueltos inválido para este comando. }
  { -* @return VPI_INVALID_OUT_PARAM Formato de algún parámetro devuelto no es correcto. }
  { -* @return VPI_GENERAL_FAIL Error general en la operación. }
  { = }
var
  vpiRefund: function(var input: vpiRefundIn_t; var output: vpiTrxOut_T;
    timeout: LongInt): Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Envía la orden de realizar una anulación de devolución y espera la respuesta }
  { -* de la misma en forma sincrónica.La aplicación queda esperando hasta tenga la }
  { -* respuesta o bien expire el timeout especificado.El puerto debe estar abierto }
  { -* para que la ejecución sea exitosa. }
  { -* @param input Estructura con los datos de entrada de la anulación. }
  { -* @param output Estructura con los datos de respuesta de la anulación. }
  { -* Se completa dentro de la función. }
  { -* @param timeout Tiempo de espera de respuesta en segundos. }
  { -* }
  { -* @return VPI_OK }
  { -* @return VPI_FAIL }
  { -* @return VPI_TIMEOUT_EXP }
  { -* @return VPI_INVALID_IN_CMD }
  { -* @return VPI_INVALID_IN_PARAM }
  { -* @return VPI_INVALID_OUT_CMD }
  { -* @return VPI_GENERAL_FAIL }
  { -* @return VPI_INVALID_ISSUER }
  { -* @return VPI_INVALID_TICKET }
  { -* @return VPI_EMPTY_BATCH }
  { -* @return VPI_TRX_CANCELED }
  { -* @return VPI_DIF_CARD }
  { -* @return VPI_INVALID_CARD }
  { -* @return VPI_EXPIRED_CARD }
  { -* @return VPI_INVALID_TRX }
  { -* @return VPI_ERR_COM }
  { -* @return VPI_ERR_PRINT }
  { = }
var
  vpiRefundVoid: function(var intput: vpiVoidIn_t; var output: vpiTrxOut_T;
    timeout: LongInt): Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Envía la orden de realizar un cierre de lote. La aplicación queda esperando hasta }
  { -* tenga la respuesta o bien expire el timeout especificado. El puerto debe estar }
  { -* abierto para que la ejecución sea exitosa. }
  { -* @param output Estructura con el resultado de la operación contra el host. }
  { -* Se completa dentro de la función. }
  { -* @param timeout Tiempo de espera de respuesta en segundos. }
  { -* }
  { -* @return VPI_OK }
  { -* @return VPI_FAIL }
  { -* @return VPI_TIMEOUT_EXP }
  { -* @return VPI_INVALID_IN_CMD }
  { -* @return VPI_INVALID_IN_PARAM }
  { -* @return VPI_INVALID_OUT_CMD }
  { -* @return VPI_GENERAL_FAIL }
  { -* @return VPI_TRX_CANCELED }
  { -* @return VPI_ERR_COM }
  { -* @return VPI_ERR_PRINT }
  { = }
var
  vpiBatchClose: function(var output: vpiBatchCloseOut_T; timeout: LongInt)
    : Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Envía la orden de obtener la información de la última transacción realizada }
  { -* y espera la respuesta de la misma en forma sincrónica.La aplicación queda }
  { -* esperando hasta tenga la respuesta o bien expire el timeout especificado. }
  { -* El puerto debe estar abierto para que la ejecución sea exitosa. }
  { -* @param trxCode Código del tipo de transacción: VPI_PURCHASE, VPI_VOID, }
  { -VPI_REFUND, VPI_REFUND_VOID }
  { -* }
  { -* @param output Estructura con los datos de respuesta de la última transacción realizada. }
  { -* Se completa dentro de la función. }
  { -* }
  { -* @return VPI_OK }
  { -* @return VPI_FAIL }
  { -* @return VPI_TIMEOUT_EXP }
  { -* @return VPI_INVALID_IN_CMD }
  { -* @return VPI_INVALID_IN_PARAM }
  { -* @return VPI_INVALID_OUT_PARAM }
  { -* @return VPI_GENERAL_FAIL }
  { -* @return VPI_INVALID_ISSUER }
  { -* @return VPI_INVALID_TICKET }
  { -* @return VPI_INVALID_PLAN }
  { -* @return VPI_EMPTY_BATCH }
  { -* @return VPI_TRX_CANCELED }
  { -* @return VPI_DIF_CARD }
  { -* @return VPI_INVALID_CARD }
  { -* @return VPI_EXPIRED_CARD }
  { -* @return VPI_ERR_COM }
  { -* @return VPI_ERR_PRINT }
  { = }
var
  vpiGetLastTrxData: function(var trxCode: Word; var output: vpiTrxOut_T)
    : Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Envía la orden de obtener un determinado registro, con los totales por tarjeta }
  { -* del último cierre realizado y espera la respuesta de la misma en forma }
  { -* sincrónica.Para obtener todos los registros se debe hacer un ciclo desde 0 }
  { -* hasta que el código de respuesta sea distinto de VPI_MORE_REC. La aplicación queda esperando }
  { -* hasta tenga la respuesta o bien expire el timeout especificado. El puerto debe }
  { -* estar abierto para que la ejecución sea exitosa. }
  { -* }
  { -* @param index Indice del registro que deseo recuperar }
  { -* @param output Estructura con la información del registro que quiero. }
  { -* }
  { -* @return VPI_OK Fin de registros. }
  { -* @return VPI_MORE_REC Quedan registros. }
  { -* @return VPI_FAIL No se pudo enviar el comando }
  { -* @return VPI_TIMEOUT_EXP Timeout de respuesta expirado sin respuesta. }
  { -* @return VPI_INVALID_INDEX El indice del registro no existe. }
  { -* @return VPI_TRX_CANCELED Transacción cancelada por el usuario. }
  { -* @return VPI_INVALID_TRX No se realizo el cierre. }
  { -* @return VPI_INVALID_IN_CMD }
  { -* @return VPI_INVALID_IN_LEN }
  { -* @return VPI_INVALID_IN_PARAM }
  { -* @return VPI_INVALID_OUT_CMD }
  { -* @return VPI_INVALID_OUT_LEN }
  { -* @return VPI_INVALID_OUT_PARAM }
  { -* @return VPI_GENERAL_FAIL }
  { = }
var
  vpiGetBatchCloseData: function(index: Word;
    var output: vpiBatchCloseDataOut_T): Word cdecl {$IFDEF WIN32} stdcall
  {$ENDIF};

  { +//* }
  { -* Envía la orden de re-imprimir el ticket de la última transacción.La aplicación queda }
  { -* esperando hasta tenga la respuesta o bien expire el timeout default.El puerto debe }
  { -* estar abierto para que la ejecución sea exitosa. }
  { -* }
  { -* @param Ninguno }
  { -* }
  { -* @return VPI_OK }
  { -* @return VPI_FAIL }
  { -* @return VPI_TIMEOUT_EXP }
  { -* @return VPI_INVALID_IN_CMD }
  { -* @return VPI_INVALID_IN_PARAM }
  { -* @return VPI_INVALID_OUT_PARAM }
  { -* @return VPI_GENERAL_FAIL }
  { = }
var
  vpiPrintTicket: function: Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Envía la orden de re-imprimir el ticket del último cierre de lote. La aplicación queda }
  { -* esperando hasta tenga la respuesta o bien expire el timeout default.El puerto debe estar }
  { -* abierto para que la ejecución sea exitosa. }
  { -* }
  { -* @param Ninguno }
  { -* }
  { -* @return VPI_OK }
  { -* @return VPI_FAIL }
  { -* @return VPI_TIMEOUT_EXP }
  { -* @return VPI_INVALID_IN_CMD }
  { -* @return VPI_INVALID_IN_PARAM }
  { -* @return VPI_INVALID_OUT_PARAM }
  { -* @return VPI_GENERAL_FAIL }
  { = }
var
  vpiPrintBatchClose: function: Word cdecl {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Envía el comando para obtener un registro de la tabla de tarjetas del POS y espera }
  { -* la respuesta de la misma en forma sincrónica. Para obtener todos los registros se }
  { -* debe hacer un ciclo desde 0 hasta que el código de respuesta sea distinto de VPI_MORE_REC. }
  { -* La aplicación queda esperando hasta tenga la respuesta o bien expire el timeout especificado. }
  { -* El puerto debe estar abierto para que la ejecución sea exitosa. }
  { -* }
  { -* @param index Indice del registro a obtener. }
  { -* @param output Estructura con los datos de la tarjeta. Se completa dentro de la función. }
  { -* }
  { -* @return VPI_OK }
  { -* @return VPI_MORE_REC }
  { -* @return VPI_FAIL }
  { -* @return VPI_TIMEOUT_EXP }
  { -* @return VPI_INVALID_IN_CMD }
  { -* @return VPI_INVALID_IN_PARAM }
  { -* @return VPI_INVALID_OUT_CMD }
  { -* @return VPI_GENERAL_FAIL }
  { -* @return VPI_INVALID_INDEX }
  { = }
var
  vpiGetIssuer: function(index: Word; var output: vpiIssuerOut_T): Word cdecl
  {$IFDEF WIN32} stdcall {$ENDIF};

  { +//* }
  { -* Envía el comando para obtener un registro de la tabla de planes del POS y espera la }
  { -* respuesta de la misma en forma sincrónica. Para obtener todos los registros se debe }
  { -* hacer un ciclo desde 0 hasta que el código de respuesta sea distinto de VPI_MORE_REC. }
  { -* La aplicación queda esperando hasta tenga la respuesta o bien expire el timeout }
  { -* especificado. El puerto debe estar abierto para que la ejecución sea exitosa. }
  { -* }
  { -* @param index Indice del registro a obtener. }
  { -* @param output Estructura con los datos del plan. Se completa dentro de la función. }
  { -* }
  { -* @return VPI_OK }
  { -* @return VPI_MORE_REC }
  { -* @return VPI_FAIL }
  { -* @return VPI_TIMEOUT_EXP }
  { -* @return VPI_INVALID_IN_CMD }
  { -* @return VPI_INVALID_IN_PARAM }
  { -* @return VPI_INVALID_OUT_CMD }
  { -* @return VPI_GENERAL_FAIL }
  { -* @return VPI_INVALID_INDEX }
  { = }
  // var
  // vpiGetPlan: function(index:word;
  // var output: VPIPLANOUT_T): Word cdecl  {$IFDEF WIN32} stdcall {$ENDIF};

var
  vpiGetPlan: function(index: Word; var output: vpiPlanOut_t): Word cdecl
  {$IFDEF WIN32} stdcall {$ENDIF};

{$ENDIF //_VPIPC_H_}

var
  DLLLoaded: Boolean { is DLL (dynamically) loaded already? }
{$IFDEF WIN32} = False; {$ENDIF}

implementation

uses Vcl.Dialogs;

var
  SaveExit: pointer;
  DLLHandle: THandle;
{$IFNDEF MSDOS}
  ErrorMode: Integer;
{$ENDIF}

procedure NewExit; far;
begin
  ExitProc := SaveExit;
  FreeLibrary(DLLHandle)
end { NewExit };

procedure LoadDLL;
begin
  if DLLLoaded then
    Exit;
{$IFNDEF MSDOS}
  ErrorMode := SetErrorMode($8000 { SEM_NoOpenFileErrorBox } );
{$ENDIF}
  DLLHandle := LoadLibrary('VPIPC.DLL');
  if DLLHandle >= 32 then
  begin
    DLLLoaded := True;
    SaveExit := ExitProc;
    ExitProc := @NewExit;
    @vpiOpenPort := GetProcAddress(DLLHandle, 'vpiOpenPort');
{$IFDEF WIN32}
    Assert(@vpiOpenPort <> nil);
{$ENDIF}
    @vpiClosePort := GetProcAddress(DLLHandle, 'vpiClosePort');
{$IFDEF WIN32}
    Assert(@vpiClosePort <> nil);
{$ENDIF}
    @vpiTestConnection := GetProcAddress(DLLHandle, 'vpiTestConnection');
{$IFDEF WIN32}
    Assert(@vpiTestConnection <> nil);
{$ENDIF}
    @vpiPurchase := GetProcAddress(DLLHandle, 'vpiPurchase');
{$IFDEF WIN32}
    Assert(@vpiPurchase <> nil);
{$ENDIF}
    @vpiVoid := GetProcAddress(DLLHandle, 'vpiVoid');
{$IFDEF WIN32}
    Assert(@vpiVoid <> nil);
{$ENDIF}
    @vpiRefund := GetProcAddress(DLLHandle, 'vpiRefund');
{$IFDEF WIN32}
    Assert(@vpiRefund <> nil);
{$ENDIF}
    @vpiRefundVoid := GetProcAddress(DLLHandle, 'vpiRefundVoid');
{$IFDEF WIN32}
    Assert(@vpiRefundVoid <> nil);
{$ENDIF}
    @vpiBatchClose := GetProcAddress(DLLHandle, 'vpiBatchClose');
{$IFDEF WIN32}
    Assert(@vpiBatchClose <> nil);
{$ENDIF}
    @vpiGetLastTrxData := GetProcAddress(DLLHandle, 'vpiGetLastTrxData');
{$IFDEF WIN32}
    Assert(@vpiGetLastTrxData <> nil);
{$ENDIF}
    @vpiGetBatchCloseData := GetProcAddress(DLLHandle, 'vpiGetBatchCloseData');
{$IFDEF WIN32}
    Assert(@vpiGetBatchCloseData <> nil);
{$ENDIF}
    @vpiPrintTicket := GetProcAddress(DLLHandle, 'vpiPrintTicket');
{$IFDEF WIN32}
    Assert(@vpiPrintTicket <> nil);
{$ENDIF}
    @vpiPrintBatchClose := GetProcAddress(DLLHandle, 'vpiPrintBatchClose');
{$IFDEF WIN32}
    Assert(@vpiPrintBatchClose <> nil);
{$ENDIF}
    @vpiGetIssuer := GetProcAddress(DLLHandle, 'vpiGetIssuer');
{$IFDEF WIN32}
    Assert(@vpiGetIssuer <> nil);
{$ENDIF}
    @vpiGetPlan := GetProcAddress(DLLHandle, 'vpiGetPlan');
{$IFDEF WIN32}
    Assert(@vpiGetPlan <> nil);
{$ENDIF}
  @vpiPurchaseExtraCash := GetProcAddress(DLLHandle, 'vpiPurchaseExtraCash');
{$IFDEF WIN32}
    Assert(@vpiPurchaseExtraCash <> nil);
{$ENDIF}

  end
  else
  begin
    DLLLoaded := False;
    { Error: VPIPC.DLL could not be loaded !! }
  end;
{$IFNDEF MSDOS}
  SetErrorMode(ErrorMode)
{$ENDIF}
end { LoadDLL };

begin
  LoadDLL;
end.
